// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel GrassTerraform

struct GrassBlade 
{
    float3 position;
    float rotation;
    float height;
    float curve;
    float3 terrainNormal;
};

struct IndirectDrawIndexedArgs
{
    uint indexCountPerInstance;
    uint instanceCount;
    uint startIndex;
    uint baseVertexIndex;
    uint startInstance;
};

RWStructuredBuffer<IndirectDrawIndexedArgs> ArgsBuffers;
StructuredBuffer<GrassBlade> OldGrassPositionsBuffer;
RWStructuredBuffer<GrassBlade> NewGrassPositionsBuffer;
StructuredBuffer<uint> OffsetsBuffer;
float3 TerraformCenter;
float TerraformRadius;
int FoliageCount;
int GrassCount;

// Perform terraformation on the region of density around the point of terraformation
[numthreads(256,1,1)]
void GrassTerraform (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;

    if (index >= GrassCount)
        return;

    int type = -1;

    for (int j = 0; j < FoliageCount; j++)
    {
        uint start = OffsetsBuffer[j];
        uint end = (j == FoliageCount - 1) ? GrassCount : OffsetsBuffer[j + 1];

        if (index >= start && index < end)
        {
            type = j;
            break;
        }
    }

    if (type == -1)
        return;

    GrassBlade blade = OldGrassPositionsBuffer[index];

    float dst = distance(blade.position, TerraformCenter);

    if (dst > TerraformRadius)
    {
        uint newIndex;
        InterlockedAdd(ArgsBuffers[type].instanceCount, 1, newIndex);

        uint globalIndex = OffsetsBuffer[type] + newIndex;

        NewGrassPositionsBuffer[globalIndex] = blade;
    }
}