// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel GrassTerraform


float3 TerraformCenter;
float3 TerraformOffset;
float TerraformRadius;
uint ChunkSize;
float3 ChunkPos;
bool TerraformMode;

// Convert a 3D array index into a 1D flat array index
int FlattenIndex(int3 id, int size) {
    return id.z * (size + 1) * (size + 1) + id.y * (size + 1) + id.x;
}
// Perform terraformation on the region of density around the point of terraformation
[numthreads(64,1,1)]
void GrassTerraform (uint3 id : SV_DispatchThreadID)
{
    uint3 localVoxelPos = TerraformOffset + id;

    if(localVoxelPos.x >= ChunkSize+1 || localVoxelPos.y >= ChunkSize+1 || localVoxelPos.z >= ChunkSize+1) {
        return ;
    }

    float3 worldVoxelPos = localVoxelPos + ChunkPos;
    float dstToCenter = length(worldVoxelPos - TerraformCenter);

    

    if(dstToCenter < TerraformRadius) {
        
    }
}
