#pragma kernel GrassCompute

struct Vertex
{
    float3 position;
    float3 normal;
};

struct Triangle
{
    Vertex v1;
    Vertex v2;
    Vertex v3;
};

struct GrassBlade 
{
    float3 position;
    float rotation;
    float height;
    float curve;
    float3 terrainNormal;
};

StructuredBuffer<Triangle> GrassTriangleBuffer;
AppendStructuredBuffer<GrassBlade> GrassPositionsBuffer1;
AppendStructuredBuffer<GrassBlade> GrassPositionsBuffer2;
AppendStructuredBuffer<GrassBlade> GrassPositionsBuffer3;
AppendStructuredBuffer<GrassBlade> GrassPositionsBuffer4;
AppendStructuredBuffer<GrassBlade> GrassPositionsBuffer5;

int TriangleCount;
int GrassDensity;

float MinHeight;
float MaxHeight;
float MaxSlope;
int MaxBladesPerTriangle;
StructuredBuffer<float2> GrassHeightRangeBuffer;
StructuredBuffer<float2> GrassCurveRangeBuffer;
StructuredBuffer<float> GrassProbabilityBuffer;

// Random hash function
float Hash(uint seed)
{
    seed ^= 2747636419u;
    seed *= 2654435769u;
    seed ^= seed >> 16;
    seed *= 2654435769u;
    seed ^= seed >> 16;
    seed *= 2654435769u;
    return (seed & 0x00FFFFFF) / 16777216.0;
}
[numthreads(256,1,1)]
void GrassCompute (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= TriangleCount) 
        return ;

    Triangle tri = GrassTriangleBuffer[id.x];
    Vertex v1 = tri.v1;
    Vertex v2 = tri.v2;
    Vertex v3 = tri.v3;

    if (v1.position.y < MinHeight || v1.position.y > MaxHeight ||
        v2.position.y < MinHeight || v2.position.y > MaxHeight ||
        v3.position.y < MinHeight || v3.position.y > MaxHeight)
            return ;

    float3 crossProd = cross(v2.position - v1.position, v3.position - v1.position);

    float3 normal = normalize(crossProd);
    if (dot(normal, float3(0,1,0)) < MaxSlope)
        return ;

    float area = length(crossProd) * 0.5;

    int bladeCount = clamp((int)(area * GrassDensity), 1, MaxBladesPerTriangle);

    float3 edge1 = v2.position - v1.position;
    float3 edge2 = v3.position - v1.position;

    uint hashSeed = id.x * 73856093u;
    float twoPie = 2 * 6.2831853;

    for (int i = 0; i < bladeCount; i++)
    {
        float r1 = Hash(hashSeed + i);
        float r2 = Hash(hashSeed + i + 1);

        if (r1 + r2 > 1.0)
        {
            r1 = 1.0 - r1;
            r2 = 1.0 - r2;
        }

        float3 pos = v1.position + r1 * edge1 + r2 * edge2;

        GrassBlade grassBlade;
        grassBlade.position = pos;
        grassBlade.terrainNormal = normal;
        grassBlade.rotation = Hash(hashSeed + i + 2) * twoPie;

        float roll = Hash(hashSeed + i + 3);
        for (int j = 0; j < 5; j++)
        {
            if ( roll <= GrassProbabilityBuffer[j]) 
            {
                grassBlade.height = lerp(GrassHeightRangeBuffer[j].x, GrassHeightRangeBuffer[j].y, Hash(hashSeed + i + 4));
                grassBlade.curve = lerp(GrassCurveRangeBuffer[j].x, GrassCurveRangeBuffer[j].y, Hash(hashSeed + i + 5));

                switch(j)
                {
                    case 0:
                        GrassPositionsBuffer1.Append(grassBlade);
                        break;
                    case 1:
                        GrassPositionsBuffer2.Append(grassBlade);
                        break;
                    case 2:
                        GrassPositionsBuffer3.Append(grassBlade);
                        break;
                    case 3:
                        GrassPositionsBuffer4.Append(grassBlade);
                        break;
                    case 4:
                        GrassPositionsBuffer5.Append(grassBlade);
                        break;
                }
                break;
            }
        }
    }
}