#pragma kernel GrassCompute
#define MAX_FOLIAGE 5
#define MAX_BLADES_PER_TRI 50

struct Vertex
{
    float3 position;
    float3 normal;
};

struct Triangle
{
    Vertex v1;
    Vertex v2;
    Vertex v3;
};

struct GrassBlade 
{
    float3 position;
    float rotation;
    float height;
    float curve;
    float3 terrainNormal;
};

struct IndirectDrawIndexedArgs
{
    uint indexCountPerInstance;
    uint instanceCount;
    uint startIndex;
    uint baseVertexIndex;
    uint startInstance;
};

StructuredBuffer<Triangle> GrassTriangleBuffer;
RWStructuredBuffer<GrassBlade> GrassPositionsBuffer;
RWStructuredBuffer<IndirectDrawIndexedArgs> ArgsBuffers;
StructuredBuffer<uint> OffsetsBuffer;

int TriangleCount;
int GrassDensity;
int FoliageCount;

float MinHeight;
float MaxHeight;
float MaxSlope;
int MaxBladesPerTriangle;
StructuredBuffer<float2> GrassHeightRangeBuffer;
StructuredBuffer<float2> GrassCurveRangeBuffer;
StructuredBuffer<float> GrassProbabilityBuffer;

// Random hash function
float Hash(uint seed)
{
    seed ^= 2747636419u;
    seed *= 2654435769u;
    seed ^= seed >> 16;
    seed *= 2654435769u;
    seed ^= seed >> 16;
    seed *= 2654435769u;
    return (seed & 0x00FFFFFF) / 16777216.0;
}
[numthreads(128,1,1)]
void GrassCompute (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= TriangleCount) 
        return ;

    Triangle tri = GrassTriangleBuffer[id.x];
    Vertex v1 = tri.v1;
    Vertex v2 = tri.v2;
    Vertex v3 = tri.v3;

    if (v1.position.y < MinHeight || v1.position.y > MaxHeight ||
        v2.position.y < MinHeight || v2.position.y > MaxHeight ||
        v3.position.y < MinHeight || v3.position.y > MaxHeight)
            return ;

    float3 crossProd = cross(v2.position - v1.position, v3.position - v1.position);

    float3 normal = normalize(crossProd);
    if (dot(normal, float3(0,1,0)) < MaxSlope)
        return ;

    float area = length(crossProd) * 0.5;

    int bladeCount = clamp((int)(area * GrassDensity), 1, MaxBladesPerTriangle);

    float3 edge1 = v2.position - v1.position;
    float3 edge2 = v3.position - v1.position;

    uint hashSeed = id.x * 73856093u;
    float twoPie = 2 * 6.2831853;

    float rolls[MAX_BLADES_PER_TRI];
    uint counts[MAX_FOLIAGE];
    uint baseOffsets[MAX_FOLIAGE];
    uint localOffsets[MAX_FOLIAGE];

    [unroll]
    for (int j = 0; j < FoliageCount; j++)
    {
        counts[j] = 0;
        baseOffsets[j] = 0;
        localOffsets[j] = 0;
    }

    for (int i = 0; i < bladeCount; i++)
    {
        float roll = Hash(hashSeed + i + 3);
        rolls[i] = roll;

        for (int j = 0; j < FoliageCount; j++)
        {
            if (roll <= GrassProbabilityBuffer[j])
            {
                counts[j]++;
                break;
            }
        }
    }

    for (int j = 0; j < FoliageCount; j++)
    {
        if (counts[j] > 0)
        {
            InterlockedAdd(ArgsBuffers[j].instanceCount, counts[j], baseOffsets[j]);
        }
    }

    for (int i = 0; i < bladeCount; i++)
    {
        float r1 = Hash(hashSeed + i);
        float r2 = Hash(hashSeed + i + 1);

        if (r1 + r2 > 1.0)
        {
            r1 = 1.0 - r1;
            r2 = 1.0 - r2;
        }

        float3 pos = v1.position + r1 * edge1 + r2 * edge2;

        GrassBlade grassBlade;
        grassBlade.position = pos;
        grassBlade.terrainNormal = normal;
        grassBlade.rotation = Hash(hashSeed + i + 2) * twoPie;

        float roll = rolls[i];
        
        for (int j = 0; j < FoliageCount; j++)
        {
            if ( roll <= GrassProbabilityBuffer[j]) 
            {
                float2 grassHeightRange = GrassHeightRangeBuffer[j];
                float2 grassCurveRange = GrassCurveRangeBuffer[j];
                grassBlade.height = lerp(grassHeightRange.x, grassHeightRange.y, Hash(hashSeed + i + 4));
                grassBlade.curve = lerp(grassCurveRange.x, grassCurveRange.y, Hash(hashSeed + i + 5));

                uint globalIndex = OffsetsBuffer[j] + baseOffsets[j] + localOffsets[j]++;

                GrassPositionsBuffer[globalIndex] = grassBlade;
                break;
            }
        }
    }
}