// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel BaseDensity
#pragma kernel ContinentalnessDensity
#pragma kernel PeaksAndValleysDensity
#pragma kernel ErosionDensity
#pragma kernel LargeCaveDensity
// #pragma use_dxc
#include "/NoiseSample.hlsl"

RWStructuredBuffer<float> HeightsBuffer;
StructuredBuffer<NoiseSettingsGPU> NoiseSettings;
// Base Noise
int BASE_INDEX = -1;
Texture2D<float> BaseCurveTexture;
// Continentalness Noise
int CONTINENTALNESS_INDEX = -1;
Texture2D<float> ContinentalnessCurveTexture;
// Peaks And Valleys Noise
int PEAKSANDVALLEYS_INDEX = -1;
Texture2D<float> PeaksAndValleysCurveTexture;
// Erosion Noise
int EROSION_INDEX = -1;
Texture2D<float> ErosionCurveTexture;
// Large Cave Noise
int LARGECAVE_INDEX = -1;
Texture2D<float> LargeCaveCurveTexture;
// Cave Detail Noise
int CAVEDETAIL_INDEX = -1;
Texture2D<float> CaveDetailCurveTexture;

int curveResolution = 256;
// Terrain Values
int height;
bool terracing;
int terraceHeight;
float isolevel;

uint ChunkSize;
float3 ChunkPos;
int MaxWorldYChunks;

// Convert a 3D array index into a 1D flat array index
int FlattenIndex(float3 id, int size) {
    return id.z * (size + 1) * (size + 1) + id.y * (size + 1) + id.x;
}

SamplerState samplerLinearClamp
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Clamp;
};

// Compute total density of terrain use provided noise data
[numthreads(4,4,4)]
void BaseDensity (uint3 id : SV_DispatchThreadID)
{

    if(id.x >= ChunkSize+1 || id.y >= ChunkSize+1 || id.z >= ChunkSize+1) {
        return ;
    }

    float3 floatID = float3(id.x, id.y, id.z);
    float terrainNoise = SampleNoise(NoiseSettings[BASE_INDEX], floatID, ChunkPos);
    float continentalnessNoise = SampleNoise(NoiseSettings[CONTINENTALNESS_INDEX], floatID, ChunkPos);
    float baseTerrainHeight = lerp(0.4, 1, (terrainNoise+1)/2);

    HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)] = baseTerrainHeight;
}

[numthreads(4,4,4)]
void ContinentalnessDensity (uint3 id : SV_DispatchThreadID)
{

    if(id.x >= ChunkSize+1 || id.y >= ChunkSize+1 || id.z >= ChunkSize+1) {
        return ;
    }

    float3 floatID = float3(id.x, id.y, id.z);
    float continentalnessNoise = SampleNoise(NoiseSettings[CONTINENTALNESS_INDEX], floatID, ChunkPos);
    float adjustedBaseTerrainHeight = HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)];

    // Continentalness
    adjustedBaseTerrainHeight = adjustedBaseTerrainHeight * (ContinentalnessCurveTexture.SampleLevel(samplerLinearClamp, (continentalnessNoise+1)/2, 0));

    HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)] = adjustedBaseTerrainHeight;
}

[numthreads(4,4,4)]
void PeaksAndValleysDensity (uint3 id : SV_DispatchThreadID)
{

    if(id.x >= ChunkSize+1 || id.y >= ChunkSize+1 || id.z >= ChunkSize+1) {
        return ;
    }

    float3 floatID = float3(id.x, id.y, id.z);
    float peaksAndValleysNoise = SampleNoise(NoiseSettings[PEAKSANDVALLEYS_INDEX], floatID, ChunkPos);
    float adjustedBaseTerrainHeight = HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)];

    adjustedBaseTerrainHeight *= PeaksAndValleysCurveTexture.SampleLevel(samplerLinearClamp, (peaksAndValleysNoise+1)/2, 0);

    HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)] = adjustedBaseTerrainHeight;
}

[numthreads(4,4,4)]
void ErosionDensity (uint3 id : SV_DispatchThreadID)
{

    if(id.x >= ChunkSize+1 || id.y >= ChunkSize+1 || id.z >= ChunkSize+1) {
        return ;
    }

    float3 floatID = float3(id.x, id.y, id.z);
    float erosionNoise = SampleNoise(NoiseSettings[EROSION_INDEX], floatID, ChunkPos);
    float adjustedBaseTerrainHeight = HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)];

    adjustedBaseTerrainHeight *= ErosionCurveTexture.SampleLevel(samplerLinearClamp, (erosionNoise+1)/2, 0);

    HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)] = adjustedBaseTerrainHeight;
}

[numthreads(4,4,4)]
void LargeCaveDensity (uint3 id : SV_DispatchThreadID)
{

    if(id.x >= ChunkSize+1 || id.y >= ChunkSize+1 || id.z >= ChunkSize+1) {
        return ;
    }

    float3 floatID = float3(id.x, id.y, id.z);
    float largeCaveNoise = SampleNoise(NoiseSettings[LARGECAVE_INDEX], floatID, ChunkPos);
    // float caveDetailNoise = SampleNoise(NoiseSettings[CAVEDETAIL_INDEX], floatID, ChunkPos);
    float adjustedBaseTerrainHeight = HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)];

    // Cave Carve Calculation
    float caveCarve = 1.0 - smoothstep(-0.4, 0.0, largeCaveNoise);
    // float smallCaveCarve =  1.0 + smoothstep(0.0, 0.2, caveDetailNoise * caveDetailNoise);
    // Terrain Density Calculation
    float currentHeight = ((height * adjustedBaseTerrainHeight) + (terracing ? (id.y%terraceHeight) : 0));
    float terrainDensity = currentHeight - (ChunkPos.y + id.y);
    // Cave Fade
    float surfaceFade = saturate((terrainDensity) / 60.0);
    float caveFade = saturate((terrainDensity - ChunkSize) / 70.0);
    float finalDensity = terrainDensity + ((ChunkPos.y + id.y) * caveFade) - (caveCarve * height * surfaceFade);
    // World Depth Fade
    if (ChunkPos.y / ChunkSize == -MaxWorldYChunks) {
        float fadeStart = ChunkSize * 0.1;
        float fadeRange = ChunkSize * 0.2;
        float worldDepthFade = saturate((id.y - fadeStart) / fadeRange);

        float caveSuppression = caveCarve * height * surfaceFade * worldDepthFade;
        finalDensity = terrainDensity + ((ChunkPos.y + id.y) * caveFade) - caveSuppression;
    }

    HeightsBuffer[FlattenIndex(float3(id.x,id.y,id.z), ChunkSize)] = finalDensity;
}